### ISSUE TITLE
If we try to access a resource before I granted it - the alias won't work

### ISSUE THREAD

**Issue by ErezWeiss** [Twingate-Labs/tg-group-profile-manager-helm#2] opened 2023-09-21 13:05 UTC
Hi guys!

We faced a problem lastly.
If we try to access a resource before I grant it with the slack app (for instance, trying to get into grafana.prod.internal)- the alias won't work after I grant it with the slack app.
Logout and Login solve the problem. 

Thanks

**Comment by emrul** [comment] 2023-09-21 13:09
Hi @ErezWeiss, did you confirm that the resource had propagated to the client (by checking the drop down list of resources in the agent)? It should take 20-30 seconds to propagate.

**Comment by ErezWeiss** [comment] 2023-09-21 13:16
Yes
And even after it shown, the alias still "remembers" that it is empty resource.

**Comment by emrul** [comment] 2023-09-21 13:20
Ok, we will investigate this and update you - thanks @ErezWeiss

**Comment by emrul** [comment] 2023-09-21 14:36
Hi @ErezWeiss - we're not able to reproduce it on our end. Is it possible the Twingate client is requiring authentication after access is granted but the notifications were disabled? In this case the Twingate icon will show with a red dot.

**Comment by ErezWeiss** [comment] 2023-09-26 07:42
@emrul 
way to reproduce:
1. try to access the resource alias when you don't have access to it.
2. Grant access to the resource and validate you have it in the client.
3. try to access it again, you will get the cached answer and not the real answer.
We are all using Mac.

**Comment by emrul** [comment] 2023-10-02 13:22
Hi @ErezWeiss - thank you for your patience with this. We believe the issue you're experiencing is unrelated to the Slackbot or Slackbot Helm chart. We believe the issue may be related to something that's specific between your environment and our product. We understand you're in touch with our support team.

For now, I'll close this issue (because GitHub is public and the issue doesn't appear to be related to our Labs projects) and our support team will follow up with you for instructions on how to collect logs so we can reproduce the issue on our end and diagnose it. We'll also be monitoring the support comms and will assist with any area that you may face issues with.

Thank you again for trying the Twingate Slackbot and we hope your issue is resolved soon!

**Closed as completed by emrul** 2023-10-02 13:22 UTC

**Comment by ErezWeiss** [comment] 2023-10-02 13:26
@emrul 
Thanks a lot!
